### ISSUE TITLE
Problem running the React Native example

### ISSUE THREAD

**Issue by amarildolucas** [semaphoreci-demos/semaphore-demo-react-native#5]
Hi @markoa, I'm opening an issue about having problems on running the app with `npm run` related to https://3.basecamp.com/3093216/buckets/11748920/todos/2723424581

**Issue 1:** The command `npm run ios` doesn't work for me either and I got a similar error. I needed to use the `npx react-native run-ios` as the React Official docs https://reactnative.dev/docs/environment-setup

**Issue 2:** The Android/iOS E2E tests are not passing because of the project configuration. For iOS, the command `applesimutils --list --byType "iPhone 11 Pro"` that is called inside `$ npm run detox-ios-test` can fall through an error for different causes:

- Not having the right simulator installed as the same you have on **package.json** file. Changing the simulator name on this file or passing it as an argument on the `npx react-native run-ios --simulator 'iPhone 11 Pro'` command will work.
- Not having installed the dependencies from https://github.com/wix/AppleSimulatorUtils until the use of any Detox e2E Test commands. After doing it, the test will pass.

I added also this Troubleshooting section on the article and make it short, but other errors can occur because the Semaphore project configuration can be different from the current user tools configuration, Android Studio virtual devices and Xcode Simulators.

```
### Troubleshooting

If you fall into some problem like this, make sure to:

1/ Run your iOS project directly in Xcode. Make sure to install all CocoaPods dependencies with `pod install` before doing this. I recommend you to search some of these repositories inside your Podfile and read their ReadMe to better be in the control of your projects. As an alternative, you can also run your iOS app with `npx react-native run-ios --simulator 'SIMULATOR_NAME'` on your console.

2/ Run your Android project in Android Studio. Check your Gradle dependencies. You can use a similar command `npx react-native run-android`. You will need to have Android Studio and Java Development Kit installed, otherwise your build will fail with the message `failed to install the app. Make sure you have the Android development environment set up`. So make sure you have the Android development environment set up.

Note: Check the Simulator names for both Android and iOS and make sure that you have them installed.
```

**Note:** In both cases the user needs to:
- For iOS, enter the iOS folder in the project and run `pod install` to install the dependencies. Open the `.xcworkspace` and build the project.
- Same for Android. Run Gradle dependencies and build the project to ensure that the configuration of the project is OK.

Anything that we run after these successful builds, even the `npm` commands that don't worked at the beginning will work now.

These are the commands that I ran to fix the errors successfully. I removed the outputs for better readability.

```
 2894  npm install OK
 2895  npm start OK
 2897  npm run lint OK
 2898  npm test OK
 2899  npm run detox-ios-build FAILED
 2900  npm run detox-ios-test FAILED
 2901  npx react-native run-ios FAILED
 2902  npx react-native run-ios --simulator 'iPhone 11 Pro' FAILED
 2904  cd ios
 2905  pod install OK
 2906  cd ..
 2908  npx react-native run-ios --simulator 'iPhone 11 Pro' PASSED (We should use the same Simulator)
 2909  npm run detox-ios-build PASSED
 2910  npm run detox-ios-test FAILED
 2911  applesimutils --list --byType "iPhone 11 Pro" FAILED, NOT INSTALLED
 2912  npx react-native run-android FAILED (following the Android Studio setup fix it) PASSED
 2913  npm run detox-android-build PASSED
 2914  npm run detox-android-test FAILED
 2915  npm run detox-ios-test FAILED
 2916  brew tap wix/brew
 2917  brew install applesimutils
 2918  npm run detox-ios-test PASSED
```

**Comment by AleksandarCole** [comment]
Hello @amarildolucas, first of all, thank you for pointing these out. 
We have updated this demo in December, cleaned it up, and made it more stable.
Can you please check it now and let me know if you still notice any issues?
